# Generated by Django 3.0.5 on 2020-04-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
        ('sub_persones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theclass',
            name='main_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opinions',
            name='sub_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_persones.SubPerson'),
        ),
        migrations.AddField(
            model_name='opinions',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.TheClass'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.TheClass'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_main_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_sub_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_persones.SubPerson'),
        ),
        migrations.AddField(
            model_name='image',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.TheClass'),
        ),
    ]
