# Generated by Django 3.0.5 on 2020-04-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sub_persones', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theclass',
            name='main_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theclass',
            name='sub_persones',
            field=models.ManyToManyField(blank=True, related_name='A', through='classes.Membership', to='sub_persones.SubPerson'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='sub_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_persones.SubPerson'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='classes.TheClass'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.TheClass'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_sub_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_persones.SubPerson'),
        ),
        migrations.AddField(
            model_name='image',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classes.TheClass'),
        ),
    ]
