# Generated by Django 3.0.5 on 2020-04-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200426_1741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membership',
            table='classes_A_the_sub_person',
        ),
    ]
