# Generated by Django 3.0.5 on 2020-04-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_auto_20200426_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='the_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='classes.TheClass'),
        ),
        migrations.AlterField(
            model_name='theclass',
            name='main_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
