# Generated by Django 3.0.5 on 2020-04-23 08:45

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200423_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='theclass',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theclass',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=classes.models.get_video_fk),
        ),
    ]
