# Generated by Django 3.0.5 on 2020-04-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_remove_membership_the_main_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='created_at',
        ),
    ]
