# Generated by Django 3.0.5 on 2020-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_persones', '0001_initial'),
        ('classes', '0006_theclass_main_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theclass',
            name='main_person',
        ),
        migrations.AddField(
            model_name='theclass',
            name='sub_persones',
            field=models.ManyToManyField(through='classes.Membership', to='sub_persones.SubPerson'),
        ),
    ]
